title: Welcome to e87042170's Homepage
description: 這裡紀錄一些學習筆記以及存放一些網頁工具.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

plugins:
  - jekyll-paginate
paginate: 10
paginate_path: "/page:num/"

navs:
- title: 首頁
  url: /

- title: 分類
  url: /categories.html

- title: 標籤
  url: /tags.html